name: Stamp
permalink: :year/:month/:day/:title
baseurl: /_site

# My Config
destination: docs/_site
incremental: false
exclude: [docs]

collections:
  diary:
    output: true

defaults:
  - scope:
      path: ""
      type: diary
    values:
      layout: post

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2017
now: 2023
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : mail@mail.com
  github : stamp-cw
  twitter : none

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   Diary: "/diary/"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-feed
